-- V10 직원명부·연차·반반차·주말근무 1.5·대체휴일
create table if not exists public.employee_registry (
  emp_no text primary key,name text not null,department text default '물류본부',
  team text,position text default '사원',annual_leave_granted numeric(6,2) default 15,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  is_active boolean default true,created_at timestamptz default now()
);
alter table public.employee_registry add column if not exists annual_leave_granted numeric(6,2) default 15;
alter table public.employee_registry enable row level security;
drop policy if exists "employee registry admin read" on public.employee_registry;
drop policy if exists "employee registry admin manage" on public.employee_registry;
create policy "employee registry admin read" on public.employee_registry for select to authenticated using(public.has_permission('employees_manage'));
create policy "employee registry admin manage" on public.employee_registry for all to authenticated using(public.has_permission('employees_manage')) with check(public.has_permission('employees_manage'));

alter table public.profiles add column if not exists annual_leave_granted numeric(6,2) default 15;
alter table public.user_permissions add column if not exists calendar_use boolean default true;
alter table public.user_permissions add column if not exists calendar_manage boolean default false;

create or replace function public.check_employee_signup(p_emp_no text,p_name text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.employee_registry;
begin
 select * into r from public.employee_registry where emp_no=trim(p_emp_no) and is_active=true;
 if r.emp_no is null then return jsonb_build_object('allowed',false,'message','등록되지 않은 사원번호입니다.'); end if;
 if r.name<>trim(p_name) then return jsonb_build_object('allowed',false,'message','사원번호와 이름이 일치하지 않습니다.'); end if;
 if r.auth_user_id is not null then return jsonb_build_object('allowed',false,'message','이미 가입된 사원번호입니다.'); end if;
 return jsonb_build_object('allowed',true);
end;$$;
grant execute on function public.check_employee_signup(text,text) to anon,authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare r public.employee_registry; v_emp text; v_name text;
begin
 v_emp:=new.raw_user_meta_data->>'emp_no'; v_name:=new.raw_user_meta_data->>'name';
 select * into r from public.employee_registry where emp_no=v_emp and name=v_name and is_active=true and auth_user_id is null for update;
 if r.emp_no is null then raise exception '등록되지 않았거나 이미 가입된 사원정보입니다.'; end if;
 insert into public.profiles(id,emp_no,name,department,team,position,annual_leave_granted,is_active)
 values(new.id,r.emp_no,r.name,r.department,r.team,r.position,r.annual_leave_granted,true);
 insert into public.user_permissions(user_id,dashboard_view,notices_view,organization_view,community_view,private_messages_use,card_use,inventory_view,purchase_view,calendar_use)
 values(new.id,true,true,true,true,true,true,true,true,true);
 update public.employee_registry set auth_user_id=new.id where emp_no=r.emp_no;
 return new;
end;$$;

create table if not exists public.work_calendar_entries(
 id bigint generated by default as identity primary key,
 employee_id uuid not null constraint work_calendar_entries_employee_id_fkey references public.profiles(id) on delete cascade,
 event_type text not null check(event_type in('off','annual','half','quarter','weekend_work','comp_used','other')),
 start_date date not null,end_date date not null,days numeric(6,2) not null default 1 check(days>0),
 memo text,created_by uuid not null references public.profiles(id),created_at timestamptz default now(),
 check(end_date>=start_date)
);
alter table public.work_calendar_entries enable row level security;
drop policy if exists "calendar own or manager read" on public.work_calendar_entries;
drop policy if exists "calendar own insert" on public.work_calendar_entries;
drop policy if exists "calendar own update" on public.work_calendar_entries;
drop policy if exists "calendar own delete" on public.work_calendar_entries;
create policy "calendar own or manager read" on public.work_calendar_entries for select to authenticated using(employee_id=auth.uid() or public.has_permission('calendar_manage'));
create policy "calendar own insert" on public.work_calendar_entries for insert to authenticated with check(employee_id=auth.uid() and created_by=auth.uid() and public.has_permission('calendar_use'));
create policy "calendar own update" on public.work_calendar_entries for update to authenticated using(employee_id=auth.uid() or public.has_permission('calendar_manage')) with check(employee_id=auth.uid() or public.has_permission('calendar_manage'));
create policy "calendar own delete" on public.work_calendar_entries for delete to authenticated using(employee_id=auth.uid() or public.has_permission('calendar_manage'));

insert into public.employee_registry(emp_no,name,department,team,position,annual_leave_granted) values
('201908011','장수범','물류본부','발주팀','사원',15),
('202004013','성경진','물류본부','발주팀','사원',15),
('202212261','함다정','물류본부','발주팀','사원',15),
('202209011','정영선','물류본부','발주팀','사원',15),
('202606081','노우석','물류본부','발주팀','사원',15),
('202107291','이찬규','물류본부','국내팀','사원',15),
('202210171','구강석','물류본부','국내팀','사원',15),
('202310161','신태선','물류본부','국내팀','사원',15),
('202304034','오정훈','물류본부','국내팀','사원',15),
('202605261','임태희','물류본부','국내팀','사원',15),
('202004012','김일신','물류본부','해외팀','사원',15),
('202209192','이형기','물류본부','해외팀','사원',15),
('202403041','김일호','물류본부','해외팀','사원',15),
('202510131','곽규탁','물류본부','해외팀','사원',15),
('202406031','김래성','물류본부','해외팀','사원',15),
('202308141','엄수현','물류본부','해외팀','사원',15),
('202512011','김상기','물류본부','해외팀','사원',15),
('202601052','김태균','물류본부','해외팀','사원',15),
('202406032','박상원','물류본부','해외팀','사원',15),
('201903022','정해림','물류본부','B2C','사원',15),
('202303021','여윤태','물류본부','B2C','사원',15),
('202303201','김지섭','물류본부','B2C','사원',15),
('202107011','이와모토마유미','물류본부','B2C','사원',15),
('202605041','김미영','물류본부','B2C','사원',15),
('202004011','김상주','물류본부','B2C','사원',15),
('202305023','이미옥','물류본부','B2C','사원',15),
('202311014','정효선','물류본부','B2C','사원',15),
('202605042','지정구','물류본부','B2C','사원',15),
('202305022','김헌정','물류본부','물류지원팀','사원',15)
on conflict(emp_no) do update set name=excluded.name,department=excluded.department,team=excluded.team,position=excluded.position,is_active=true;

update public.user_permissions set calendar_use=true,calendar_manage=true where user_id in(select id from public.profiles where is_super_admin=true);
