-- V11 조직도 홈페이지 수정 기능
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.organization_teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer default 99,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.organization_teams enable row level security;

drop policy if exists "organization teams readable" on public.organization_teams;
drop policy if exists "organization teams managed" on public.organization_teams;

create policy "organization teams readable"
on public.organization_teams for select to authenticated
using (public.has_permission('organization_view'));

create policy "organization teams managed"
on public.organization_teams for all to authenticated
using (public.has_permission('employees_manage'))
with check (public.has_permission('employees_manage'));

insert into public.organization_teams(name,sort_order) values
('관리',1),
('발주팀',10),
('국내팀',20),
('해외팀',30),
('B2C',40),
('물류지원팀',50)
on conflict(name) do update set sort_order=excluded.sort_order;

-- 현재 직원의 표시순서가 비어 있을 경우 기본값 설정
update public.profiles
set sort_order=999
where sort_order is null;
