-- V33 근무·휴무 달력 전체 설치
-- work_calendar_entries 테이블이 없어 발생한 오류를 해결합니다.

create table if not exists public.work_calendar_entries (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'annual',
      'half',
      'quarter',
      'off',
      'weekend_work',
      'comp_used',
      'other'
    )
  ),
  start_date date not null,
  end_date date not null,
  days numeric(6,2) not null default 1,
  memo text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists idx_work_calendar_employee
on public.work_calendar_entries(employee_id);

create index if not exists idx_work_calendar_dates
on public.work_calendar_entries(start_date,end_date);

alter table public.work_calendar_entries enable row level security;

drop policy if exists "calendar own or manager read" on public.work_calendar_entries;
create policy "calendar own or manager read"
on public.work_calendar_entries
for select
to authenticated
using (
  employee_id=auth.uid()
  or public.is_super_admin()
  or public.has_permission('calendar_manage')
);

drop policy if exists "calendar own or manager insert" on public.work_calendar_entries;
create policy "calendar own or manager insert"
on public.work_calendar_entries
for insert
to authenticated
with check (
  (
    employee_id=auth.uid()
    and created_by=auth.uid()
  )
  or public.is_super_admin()
  or public.has_permission('calendar_manage')
);

drop policy if exists "calendar own or manager update" on public.work_calendar_entries;
create policy "calendar own or manager update"
on public.work_calendar_entries
for update
to authenticated
using (
  employee_id=auth.uid()
  or public.is_super_admin()
  or public.has_permission('calendar_manage')
)
with check (
  employee_id=auth.uid()
  or public.is_super_admin()
  or public.has_permission('calendar_manage')
);

drop policy if exists "calendar own or manager delete" on public.work_calendar_entries;
create policy "calendar own or manager delete"
on public.work_calendar_entries
for delete
to authenticated
using (
  employee_id=auth.uid()
  or public.is_super_admin()
  or public.has_permission('calendar_manage')
);

grant select,insert,update,delete
on public.work_calendar_entries
to authenticated;

grant usage,select
on sequence public.work_calendar_entries_id_seq
to authenticated;

notify pgrst, 'reload schema';
