-- 서린 물류포털 V37 구매관리 전체 설치
-- 적용 흐름: 직원 신청 → 김헌정 검토 → 손동오 승인 → 김헌정 발주·입고·구매완료
-- Supabase SQL Editor에서 전체 실행하세요.

begin;

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id),
  item_name text not null,
  quantity numeric(14,2) default 1,
  estimated_amount numeric(14,2),
  created_at timestamptz default now()
);

alter table public.purchase_requests
  add column if not exists requester_emp_no text,
  add column if not exists requester_name text,
  add column if not exists unit text,
  add column if not exists needed_date date,
  add column if not exists is_urgent boolean default false,
  add column if not exists purpose text,
  add column if not exists memo text,
  add column if not exists status text default 'requested',
  add column if not exists reviewer_id uuid references public.profiles(id),
  add column if not exists reviewer_name text,
  add column if not exists reviewed_at timestamptz,
  add column if not exists approver_id uuid references public.profiles(id),
  add column if not exists approver_name text,
  add column if not exists approved_at timestamptz,
  add column if not exists ordered_at timestamptz,
  add column if not exists received_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists reject_reason text,
  add column if not exists rejected_at timestamptz,
  add column if not exists updated_at timestamptz default now();

-- 기존 V1 상태값과 컬럼을 V37 형식으로 변환
update public.purchase_requests
set purpose = coalesce(purpose, reason)
where purpose is null and reason is not null;

update public.purchase_requests
set status = case status
  when '대기' then 'requested'
  when '승인' then 'approved'
  when '반려' then 'rejected'
  when '구매완료' then 'completed'
  else status
end
where status in ('대기','승인','반려','구매완료');

-- 예전 status CHECK 제약조건 제거
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid='public.purchase_requests'::regclass
      AND contype='c'
      AND pg_get_constraintdef(oid) ilike '%status%'
  LOOP
    EXECUTE format('alter table public.purchase_requests drop constraint if exists %I',r.conname);
  END LOOP;
END $$;

alter table public.purchase_requests
  add constraint purchase_requests_status_check
  check (status in ('requested','reviewing','review_complete','approved','ordered','received','completed','rejected'));

alter table public.purchase_requests alter column status set default 'requested';
alter table public.purchase_requests alter column status set not null;

create index if not exists idx_purchase_requests_requester on public.purchase_requests(requester_id);
create index if not exists idx_purchase_requests_status on public.purchase_requests(status);
create index if not exists idx_purchase_requests_created_at on public.purchase_requests(created_at desc);

-- 신청자 표시정보 자동 보완
create or replace function public.fill_purchase_requester_info()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare p public.profiles%rowtype;
begin
  select * into p from public.profiles where id=new.requester_id;
  new.requester_emp_no := coalesce(nullif(new.requester_emp_no,''),p.emp_no);
  new.requester_name := coalesce(nullif(new.requester_name,''),p.name);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_fill_purchase_requester_info on public.purchase_requests;
create trigger trg_fill_purchase_requester_info
before insert or update on public.purchase_requests
for each row execute function public.fill_purchase_requester_info();

-- RLS 재설정
alter table public.purchase_requests enable row level security;
drop policy if exists "purchase own or approver read" on public.purchase_requests;
drop policy if exists "purchase request insert" on public.purchase_requests;
drop policy if exists "purchase approver update" on public.purchase_requests;
drop policy if exists "V37 purchase select" on public.purchase_requests;
drop policy if exists "V37 purchase insert" on public.purchase_requests;

create policy "V37 purchase select" on public.purchase_requests
for select to authenticated
using (
  requester_id=auth.uid()
  or public.has_permission('purchase_approve')
  or public.is_super_admin()
);

create policy "V37 purchase insert" on public.purchase_requests
for insert to authenticated
with check (
  requester_id=auth.uid()
  and public.has_permission('purchase_view')
  and status='requested'
);

-- 상태변경은 아래 RPC만 사용합니다.
revoke update, delete on public.purchase_requests from authenticated;
grant select, insert on public.purchase_requests to authenticated;

create or replace function public.update_purchase_request_status(
  p_request_id bigint,
  p_status text,
  p_reason text default null
)
returns public.purchase_requests
language plpgsql
security definer
set search_path=public
as $$
declare
  v_row public.purchase_requests%rowtype;
  v_actor public.profiles%rowtype;
  v_is_super boolean;
  v_is_manager boolean;
begin
  select * into v_actor from public.profiles where id=auth.uid();
  if v_actor.id is null then raise exception '로그인 사용자 정보를 찾을 수 없습니다.'; end if;

  v_is_super := coalesce(v_actor.is_super_admin,false);
  v_is_manager := public.has_permission('purchase_approve') and not v_is_super;

  select * into v_row from public.purchase_requests where id=p_request_id for update;
  if v_row.id is null then raise exception '구매 신청 건을 찾을 수 없습니다.'; end if;

  if p_status not in ('reviewing','review_complete','approved','ordered','received','completed','rejected') then
    raise exception '허용되지 않은 상태입니다.';
  end if;

  -- 김헌정 등 구매담당자 처리
  if v_is_manager then
    if p_status='reviewing' and v_row.status<>'requested' then
      raise exception '신청 상태에서만 검토를 시작할 수 있습니다.';
    elsif p_status='review_complete' and v_row.status not in ('requested','reviewing') then
      raise exception '신청 또는 검토중 상태에서만 검토완료할 수 있습니다.';
    elsif p_status='ordered' and v_row.status<>'approved' then
      raise exception '승인완료 상태에서만 발주완료할 수 있습니다.';
    elsif p_status='received' and v_row.status<>'ordered' then
      raise exception '발주완료 상태에서만 입고완료할 수 있습니다.';
    elsif p_status='completed' and v_row.status<>'received' then
      raise exception '입고완료 상태에서만 구매완료할 수 있습니다.';
    elsif p_status='approved' then
      raise exception '최종 승인은 최고관리자만 할 수 있습니다.';
    elsif p_status='rejected' and v_row.status not in ('requested','reviewing','review_complete','approved') then
      raise exception '현재 상태에서는 반려할 수 없습니다.';
    end if;
  -- 손동오 최고관리자 처리
  elsif v_is_super then
    if p_status='approved' and v_row.status<>'review_complete' then
      raise exception '김헌정 검토완료 후에만 승인할 수 있습니다.';
    elsif p_status='rejected' and v_row.status<>'review_complete' then
      raise exception '승인대기 상태에서만 반려할 수 있습니다.';
    elsif p_status not in ('approved','rejected') then
      raise exception '최고관리자는 최종 승인 또는 반려만 처리합니다.';
    end if;
  else
    raise exception '구매 처리 권한이 없습니다.';
  end if;

  if p_status='rejected' and coalesce(trim(p_reason),'')='' then
    raise exception '반려 사유를 입력하세요.';
  end if;

  update public.purchase_requests
  set status=p_status,
      reviewer_id=case when p_status in ('reviewing','review_complete') then auth.uid() else reviewer_id end,
      reviewer_name=case when p_status in ('reviewing','review_complete') then v_actor.name else reviewer_name end,
      reviewed_at=case when p_status='review_complete' then now() else reviewed_at end,
      approver_id=case when p_status='approved' then auth.uid() else approver_id end,
      approver_name=case when p_status='approved' then v_actor.name else approver_name end,
      approved_at=case when p_status='approved' then now() else approved_at end,
      ordered_at=case when p_status='ordered' then now() else ordered_at end,
      received_at=case when p_status='received' then now() else received_at end,
      completed_at=case when p_status='completed' then now() else completed_at end,
      reject_reason=case when p_status='rejected' then trim(p_reason) else reject_reason end,
      rejected_at=case when p_status='rejected' then now() else rejected_at end,
      updated_at=now()
  where id=p_request_id
  returning * into v_row;

  insert into public.audit_logs(user_id,action,table_name,record_id,details)
  values(auth.uid(),'PURCHASE_STATUS_CHANGE','purchase_requests',p_request_id::text,
    jsonb_build_object('status',p_status,'reason',p_reason,'actor',v_actor.name));

  return v_row;
end;
$$;

grant execute on function public.update_purchase_request_status(bigint,text,text) to authenticated;

-- 김헌정(202305022)을 구매담당자로 지정합니다. 가입 완료 상태일 때 자동 반영됩니다.
insert into public.user_permissions(user_id,purchase_view,purchase_approve)
select id,true,true from public.profiles where emp_no='202305022'
on conflict(user_id) do update
set purchase_view=true,purchase_approve=true,updated_at=now();

commit;

-- 확인용
select p.emp_no,p.name,up.purchase_view,up.purchase_approve
from public.profiles p
left join public.user_permissions up on up.user_id=p.id
where p.emp_no in ('EMP001','emp001','202305022');
