-- 서린컴퍼니 V45 통합업무관리 설치 SQL
create extension if not exists pgcrypto;

create table if not exists public.company_events(id uuid primary key default gen_random_uuid(),event_type text not null default 'company',title text not null,start_date date not null,end_date date not null,event_time text,manager_name text,participant_count integer not null default 0,location text,memo text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.meeting_room_bookings(id uuid primary key default gen_random_uuid(),room_name text not null default '회의실',meeting_date date not null,start_time time not null,end_time time not null,title text not null,organizer_name text,meeting_with text,attendees text,memo text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),constraint meeting_time_valid check(end_time>start_time));
create table if not exists public.fleet_vehicles(id uuid primary key default gen_random_uuid(),vehicle_name text not null,vehicle_number text not null unique,manager_name text,current_mileage numeric not null default 0,insurance_expiry date,inspection_expiry date,status text not null default '운행가능',memo text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vehicle_trip_logs(id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.fleet_vehicles(id) on delete cascade,trip_date date not null,department text,driver_name text not null,start_place text,end_place text,purpose_address text,distance_km numeric not null default 0,odometer_km numeric not null default 0,fuel_cost numeric not null default 0,memo text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.vehicle_maintenance(id uuid primary key default gen_random_uuid(),vehicle_id uuid not null references public.fleet_vehicles(id) on delete cascade,maintenance_date date not null,maintenance_type text not null,mileage_km numeric not null default 0,shop_name text,cost numeric not null default 0,next_due_date date,next_due_mileage numeric,memo text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());

insert into public.fleet_vehicles(vehicle_name,vehicle_number,status) values('모하비','22우8010','운행가능'),('벤츠','215서1806','운행가능'),('스포티지','174하9138','운행가능'),('스타리아','807노5770','운행가능') on conflict(vehicle_number) do nothing;

alter table public.company_events enable row level security;alter table public.meeting_room_bookings enable row level security;alter table public.fleet_vehicles enable row level security;alter table public.vehicle_trip_logs enable row level security;alter table public.vehicle_maintenance enable row level security;

do $$ declare t text; begin foreach t in array array['company_events','meeting_room_bookings','fleet_vehicles','vehicle_trip_logs','vehicle_maintenance'] loop execute format('drop policy if exists %I on public.%I',t||'_read',t);execute format('create policy %I on public.%I for select to authenticated using (true)',t||'_read',t); end loop; end $$;

drop policy if exists company_events_write on public.company_events;create policy company_events_write on public.company_events for all to authenticated using(public.is_super_admin() or public.has_permission('calendar_manage')) with check(public.is_super_admin() or public.has_permission('calendar_manage'));
drop policy if exists meeting_insert on public.meeting_room_bookings;create policy meeting_insert on public.meeting_room_bookings for insert to authenticated with check(created_by=auth.uid());drop policy if exists meeting_update on public.meeting_room_bookings;create policy meeting_update on public.meeting_room_bookings for update to authenticated using(created_by=auth.uid() or public.is_super_admin() or public.has_permission('calendar_manage'));drop policy if exists meeting_delete on public.meeting_room_bookings;create policy meeting_delete on public.meeting_room_bookings for delete to authenticated using(created_by=auth.uid() or public.is_super_admin() or public.has_permission('calendar_manage'));

do $$ declare t text; begin foreach t in array array['fleet_vehicles','vehicle_trip_logs','vehicle_maintenance'] loop execute format('drop policy if exists %I on public.%I',t||'_write',t);execute format('create policy %I on public.%I for all to authenticated using (public.is_super_admin() or public.has_permission('employees_manage')) with check (public.is_super_admin() or public.has_permission('employees_manage'))',t||'_write',t); end loop; end $$;

grant select,insert,update,delete on public.company_events,public.meeting_room_bookings,public.fleet_vehicles,public.vehicle_trip_logs,public.vehicle_maintenance to authenticated;
