-- 서린 물류 포털 V8
-- 조직도·비상연락망·실시간 직원 소통방 추가
-- Supabase SQL Editor에서 전체 실행하세요.

alter table public.profiles
  add column if not exists emergency_contact_name text,
  add column if not exists emergency_contact_relation text,
  add column if not exists emergency_contact_phone text;

alter table public.user_permissions
  add column if not exists emergency_contacts_view boolean default false;

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null
    constraint chat_messages_sender_id_fkey
    references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_created_at_idx
  on public.chat_messages(created_at desc);

create index if not exists chat_messages_sender_id_idx
  on public.chat_messages(sender_id);

alter table public.chat_messages enable row level security;

drop policy if exists "chat readable by allowed employees" on public.chat_messages;
drop policy if exists "chat insert by allowed employees" on public.chat_messages;
drop policy if exists "chat delete own message" on public.chat_messages;

create policy "chat readable by allowed employees"
on public.chat_messages for select to authenticated
using (public.has_permission('community_view'));

create policy "chat insert by allowed employees"
on public.chat_messages for insert to authenticated
with check (
  sender_id = auth.uid()
  and public.has_permission('community_view')
);

create policy "chat delete own message"
on public.chat_messages for delete to authenticated
using (
  sender_id = auth.uid()
  or public.is_super_admin()
);

-- Realtime Postgres Changes 활성화
do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
end $$;

-- EMP001 최고관리자에게 비상연락망 권한 부여
update public.user_permissions
set emergency_contacts_view = true
where user_id = (
  select id from public.profiles where emp_no = 'EMP001' limit 1
);
